Adding extra logging on import parts of the Cronjob
mailchimp/mc-magento2 pull request #377
Opened 2018-08-27 00:38 UTC by maximbaibakov

Adding extra logging on import parts of the Cronjob.

There is a bit lack of visibility around execution of the sync process.
Would be awesome to see where the sync spends more time and helps to diagnose, if the sync stuck somewhere due to some reason.

E.g. Reasons:
- Payload was not able to generate due to M2 Core issue and failed with warning or fatal error
- You can see how much time been spent on specific part e.g. products, orders and etc. It helped me to diagnose that cart generation was taking about 20 minutes to generate due to some slow SQL query

2018-09-12 17:55 UTC, gonzaloebiz requested changes
Please open an issue for the extra logging issue and delete the extra commit for the temp directory (this is in a separate issue and already accepted)

2018-09-13 10:36 UTC, maximbaibakov commented
Hi @gonzaloebiz 

Thanks for the review. Issue has been created: https://github.com/mailchimp/mc-magento2/issues/393

PR has been adjusted

Regards,
Maxim

2018-09-13 11:31 UTC, gonzaloebiz approved these changes

2018-09-13 11:31 UTC, merged

2018-09-13 11:32 UTC, gonzaloebiz commented
Hi @maximbaibakov 

thanks for your contribution