bugfix STOREID null for error: "Data did not match any of the schemas described in anyOf."
mailchimp/mc-magento2 pull request #76
Opened 2017-08-30 09:32 UTC by elisongit

If customer subscribe newsletter as a guest, the variable $subscriber in the function beforeSubscribe (class Ebizmarts/MailChimp/Model/Plugin/Subscriber.php) has storeId null. This situation generate error "Data did not match any of the schemas described in anyOf." when module calls api for add subscribe in mailchimp.

We set storeId for resolve issue. For our company policy we modified also composer version because we editing a module third parts.

2017-08-30 20:41 UTC, gonzaloebiz commented
Please, don't change the version.

2017-09-18 19:15 UTC, centerax requested changes

2017-09-18 19:15 UTC, centerax commented on composer.json
> +  "version": "1.0.21.1",
please see Gonzalo's comment. remove this change and the pr can be merged.

2017-09-20 07:51 UTC, elisongit commented
Thanks for reply, we add fourth digit in version composer for manage bugfix in third part modules.
Furthermore we installed Magento via composer and to download the updated version of module is necessary we modify the version in composer.json because composer checks version in composer.json to download module.

2017-09-21 13:55 UTC, gonzaloebiz requested changes
Please, don't change the version

2017-10-24 11:52 UTC, gonzaloebiz commented
One month without news, so i close the PR

2017-10-24 11:52 UTC, closed without merging